[versions]
gratatouille-runtime = "0.1.2"
gratatouille-build-time = "0.1.3-SNAPSHOT-ece70695061b18da18165c5203a180d1382abcbe"
# Version of KGP we are using to build tapmoc
kgp-latest = "2.2.20"
ksp = "2.2.20-2.0.4"
# Version of KGP tapmoc is compatible with at runtime
kgp-compile-only = "1.9.0"
compile-sdk = "36"
agp9 = "9.0.0-beta02"
nmcp = "1.3.1-SNAPSHOT-bd3a2d8eeaa63dce9dfc2c9d8b63f4a2a98a50e7"

[libraries]
#noinspection AndroidGradlePluginVersion
gradle-api = "dev.gradleplugins:gradle-api:8.0"
#noinspection AndroidGradlePluginVersion
agp = "com.android.tools.build:gradle:8.2.0"
kgp-compile-only = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kgp-compile-only" }
gratatouille-tasks-runtime = { module = "com.gradleup.gratatouille:gratatouille-tasks-runtime", version.ref = "gratatouille-runtime" }
gratatouille-wiring-runtime = { module = "com.gradleup.gratatouille:gratatouille-wiring-runtime", version.ref = "gratatouille-runtime" }
kotlin-metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kgp-latest" }
cast = "net.mbonnin.cast:cast:0.0.1"
jsonpathkt = "com.eygraber:jsonpathkt-kotlinx:3.0.2"
kotlinx-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"
asm = "org.ow2.asm:asm:9.9"
tapmoc = "com.gradleup.tapmoc:tapmoc-gradle-plugin:0.0.3"
nmcp-tasks = { module = "com.gradleup.nmcp:nmcp-tasks", version.ref = "nmcp" }

[plugins]
kgp-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kgp-latest" }
kgp-android = { id = "org.jetbrains.kotlin.android", version.ref = "kgp-latest" }
kgp-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kgp-latest" }
#noinspection SimilarGradleDependency
agp8 = { id = "com.android.library", version = "8.13.0" }
agp9-kmp = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp9" }
#noinspection SimilarGradleDependency
agp9-library = { id = "com.android.library", version.ref = "agp9" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
librarian = { id = "com.gradleup.librarian", version = "0.2.2-SNAPSHOT-6898196f1f9759091ae6fa9bbe84154ec28a9331" }
#noinspection NewerVersionAvailable
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
#noinspection NewerVersionAvailable
tapmoc = { id = "com.gradleup.compat.patrouille", version = "0.0.1-SNAPSHOT-6757526acb8472d098bed30aa17531d7f127571f" }
gratatouille = { id = "com.gradleup.gratatouille", version.ref = "gratatouille-build-time" }
