on: pull_request

jobs:
  build-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - run: |
          ./gradlew build
          ./gradlew -p tests/agp8-java build
          ./gradlew -p tests/agp8-kotlin build
          ./gradlew -p tests/agp9-kmp build
          ./gradlew -p tests/agp9-kotlin build
          ./gradlew -p tests/java build
          ./gradlew -p tests/jvm build
          ./gradlew -p tests/wasm-js build
